- name: Container handling
  block:
    - name: Stop Docker container
      docker_container:
        name: "{{ container_name }}"
        state: stopped
      tags:
        - remove-container

    - name: Remove Docker container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      tags:
        - remove-container
  rescue:
    - name: Printing error
      ansible.builtin.debug:
        msg: "Error occurred when removing container. It means that container is already wiped."

- name: Image handling
  block:
    - name: Remove Docker image
      docker_image:
        name: "{{ web_image }}"
        state: absent
      tags:
        - remove-image
  rescue:
    - name: Printing error
      ansible.builtin.debug:
        msg: "Error occurred when removing image. It means that image is already wiped."

