apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-app
  template:
    metadata:
      labels:
        app: time-app
    spec:
      containers:
      - name: time-app-container
        image: glebuben/dev-ops-labs:latest
        ports:
        - containerPort: 5000
