---
- name: Setup Docker APT Repository and GPG Key
  block:
    - name: Add Docker APT repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      tags:
        - apt-repo

    - name: Add Docker's official GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - gpg-key
  tags:
    - docker
    - docker-setup

- name: Install requirements
  block:
    - name: Install pip
      become: true
      apt:
        name: python3-pip
        state: present
      tags:
        - pip

    - name: Install Docker dependencies
      become: true
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      tags:
        - docker
        - dependencies

    - name: Install Docker
      become: true
      apt:
        name: docker-ce
        state: present
      tags:
        - docker
  tags:
    - install